version: '3'

services:
  web:
    build:
      context: .
      args:
        - ALGOLIA_API_KEY=${ALGOLIA_API_KEY}
    image: psrandom:1.0
    entrypoint: .docker/entrypoint.sh
    command: bundle exec jekyll serve -H 0.0.0.0 -t --force_polling --livereload --drafts
    volumes:
      - .:/srv/jekyll
      # - ~/.aws:/home/jekyll/.aws
      #- ./vendor/bundle:/usr/local/bundle
      #- ./vendor/theme:/tmp
    ports:
      - 4000:4000
      - 35729:35729
    user: "1000:1000"
    env_file:
      - .env